- package-lock.json
- package.json
- src/index.html
- src/js/App.svelte
- src/js/Button.svelte
- src/js/svelte.js
- vite.config.js
Is this the best way to add svelte to an existing vite project? Maybe not. But Rich Harris worked on this [vite-plugin-svelte](https://github.com/sveltejs/vite-plugin-svelte) plugin, so I felt it was probably safe enough.
It looks like I changed a bunch of stuff in `index.html` but I'm pretty sure that's just my awful linter. I added lines 66 and 68:
> add svelte to existing vite + bootstrap

- src/js/components/AdvancedSearchForm/index.svelte
- src/js/components/FilterableSelection.svelte
- src/js/components/LoginFormModal/index.svelte
- src/js/designs/ResultsItem/index.svelte
- src/scss/styles.scss
All about login:
* have the login modal default to using the `sdrinst` from `HT.prefs`
* if `filterText` is passed to `FilterableSelection`, check that item and filter the list
* add a "clear filter" button to the filter input
All about accordions:
* remove the active background color from `accordion-header`
* tweak the padding so header and body elements align
* remove `accordion-body` padding if it contains a `list-group` (see example)
> DEV-682 - grab bag of small tweaks

- src/js/components/Header/index.svelte
- src/js/components/Modal/index.svelte
- src/js/designs/TwoColumnLayout/index.svelte
- src/js/main.js
- src/scss/apps.scss
- ironing out the search bar toggle state
- have the `dialog` be inert and `aria-hidden="true"` if it's not visible
- add styles to hide filters unless toggled open
- have `main.js` toggle filter visibility
The Designs > Two Column Layout > Narrow story demonstrates the filter toggle.
> Tweaks for reader and responsive

- src/js/main.js
- src/scss/apps.scss
Added support  to `main.js` and `apps.scss`  to look for buttons with `data-action="expand-filter"`, which will handle the the "show all filter" element.
That filter button needs to look like the Smary version of this XSLT snippet --- configuring `span.not-expanded` and `span.is-expanded`. 
```
<button type="button" class="btn btn-sm btn-outline-dark" data-action="expand-filter" aria-expanded="false">
<span>
Show 
<span class="not-expanded">
<xsl:text> all </xsl:text>
<xsl:value-of select="$total" />
<xsl:text> </xsl:text>
</span>
<span class="is-expanded"> fewer </span>
<xsl:value-of select="$filter/@name" />
<xsl:text> Filters</xsl:text>
</span>
</button>
```
> DEV-753 - add data-action=expand-filters support

- src/js/components/FeedbackFormModal/FeedbackFormModal.stories.js
- src/js/components/FeedbackFormModal/index.svelte
- src/js/components/Navbar/index.svelte
This is basic/MVP, definitely needs more dynamic behavior when we have time to add.
Getting location from `data-app` attribute on `<html>` element. If catalog, "Report a bug" link shows the catalog quality correction form. If pt, the same link shows content correction form. Anywhere else, "report a bug" will show the basic/general "Questions?" form. "Ask a question" gives the basic/general form regardless of location.
Could use more nuance! I'd like to continue work on this, but we'll see what we have time for in the end.
> Firebird task: feedback form as modal for header

- src/js/components/AcceptableUseBanner/index.svelte
- src/js/components/AdvancedSearchForm/index.svelte
- src/js/components/ResultsPagination/index.svelte
- src/js/components/ResultsToolbar/index.svelte
DEV-772 - updated the pagination to be less heavy and reflect our rounded-shadow motifs; it also is not sticky when the viewport is <= 600px in either dimension. (To be tuned later.)
Setting that seemed to fix the AUP? Or something.
DEV-776: adjusted the padding on the advanced search selects so they didn't overlap the caret on narrow viewports.
While I was there, refined the `onMount` behavior to fill in more fields, and added the option to use the full text index.
> DEV-772-776 + searching full text index

- src/js/lib/analytics.js
- src/js/main.js
`ping` will send analytics configuration managed in `/htapps/babel/etc/settings/ping/analytics.json`, and analytics will be configured if there's configuration.
> add analytics if ping sends container

- package-lock.json
- package.json
- src/js/components/Modal/index.svelte
Adds https://github.com/GoogleChrome/dialog-polyfill and registers it as needed. Annoyingly has to be applied to every `<dialog>` element and has been folded into the Modal component.
> Add dialog polyfill for modals

- .gitignore
- src/js/components/AdvancedSearchForm/index.svelte
As I understand it, the problem is that regardless of search history or how a user arrives on (catalog?) advanced search, the full-view only checkbox is always toggled to checked/true (via `isFullView` variable). 
The solution @moseshll requested (and I think is probably the easiest solution) is to check the URL parameters for `ft=ft` and set `isFullView` from that. 
I think I did that! Thanks to my linter hating Roger's linter, it looks like I changed a bunch of stuff, but it's really just lines 298-300:
```js
if (!params.get('ft')) {
isFullView = false;
}
```
Next steps?
> DEV-918: fix catalog advanced search full-view checkbox

- src/js/components/Navbar/index.svelte
When in catalog (or website), if user chooses to switch roles via the navbar login/account button, the user is sent back to the website homepage instead of the page they were on. 
`/components/Navbar/index.js` (line 434)
```js
href="//{`${
HT.service_domain
}/cgi/ping/switch?target=${encodeURIComponent(
window.location.href
)}`}"
```
I borrowed the code from Roger's logout redirect just below this in the same file.
`babel-local-dev` doesn't have `ping` (or at least mine doesn't), so I tested this on https://dev-3.catalog.hathitrust.org/Search/Home 
Conduct search, open catalog record, log in and switch role to CAA-- you should be redirected back to the page you were on.
> DEV-925: update switch role link

- src/js/lib/analytics.js
I added the javascript [matomo suggests for this type of thing](https://matomo.org/faq/how-to/how-do-i-set-a-custom-page-title-using-the-matomo-javascript-title/) to the firebird analytics file. 
This is staged on dev-3 and you can "test" it on any pageturner item, but the results only show up on testing.matomo. Here's a screenshot from my "visitor profile" showing that the titles used to have seq # in them, and now they don't!
> DEV-896: matomo custom page title

- .storybook/main.js
- .storybook/preview-head.html
Removed font-awesome script from storybook preview head tag. I also updated the storybook config to set the static asset directory path in case we need that in the future.
> remove font awesome script

- package.json
- src/js/components/FeedbackFormModal/FeedbackFormModal.stories.js
- src/js/components/FeedbackFormModal/index.svelte
I used Roger's [date logic](https://github.com/hathitrust/common/blob/463fb5facb7f6796898373e9c0404910ca3d9f5b/web/alicorn/src/js/components/feedback.js#L60) from alicorn and Val's suggested wording to create a message for the form that will only show between two dates (in this case Dec 22 - Jan 2). I added a few stories to the storybook, too. 
Take a look at the [deploy preview on netlify](https://deploy-preview-55--hathitrust-firebird-common.netlify.app/storybook/?path=/story/feedback-form-modal--winter-break). This links to the Winter Break story, but there is also a `winterBreak` variable on the other versions of the feedback form modal, so you can toggle the message on and off to see what it will look like in each variant of the modal. I deployed this on dev-3, but it's hard to see …
> Winter break message for feedback form

- src/js/components/AdvancedSearchForm/index.svelte
When working on Advanced Search locally, the search part doesn't actually work thanks to the hard-coded `https` protocol. This update adds a check for the current `location.protocol`, then builds the search URL using `https` if that's the current protocol, otherwise falls back to `http`.
This is up on `dev-3` and looks like it's working. 
- [dev 3 `ls` advanced search](https://dev-3.babel.hathitrust.org/cgi/ls?a=page&page=advanced)
- [dev 3 `catalog` advanced search](https://dev-3.catalog.hathitrust.org/Search/Advanced)
But I'm interested to see if anyone can get my changes working locally with my new babel-local-dev firebird workflow.
Perhaps:
1. in `/babel/firebird-common`, `git fetch` and switch to the `TTO-166` branch
2. `docker compose run node bash` will drop you into a `I have no …
> update search URLs to use location protocol

- src/scss/apps.scss
In the future, the visbility and text of the alert banner should be driven by something external, but this seems like the simplest change to hide it for the time being.
> Hide alert banner

- src/js/components/CookieConsentBanner/CookieConsentBanner.stories.js
- src/js/components/CookieConsentBanner/index.svelte
- vite.config.js
After conversation with Ange and Gayathri, we decided to update the cookie banner to implement non-modal dialog best practices:
- add a close button
- remove `<section>` and use a div with `role=dialog` and `aria-modal=false`
- implement focus-trapping for keyboard users
With this PR, the banner has been updated to use a close button and focus trap.
> update a11y for cookie banner

- src/js/components/AlertBanner/AlertBanner.stories.js
- src/js/components/AlertBanner/index.svelte
- src/js/components/CookieConsentBanner/index.svelte
- src/scss/styles.scss
Wrapping up DEV-1095:
- added a close button that dismisses the banner
- the dismiss function also sets a 14-day cookie "HT-alert-[id#]" to "dismiss" if users have allowed preference cookies
- cleaned up component markup
- edited component to use JSON data so we can easily swap in a JSON file later
See visual review of component in chromatic here: https://www.chromatic.com/review?appId=656a2bfa011def621f569319&number=70&type=linked&view=changes
And interactive component in chromatic here: https://www.chromatic.com/component?appId=656a2bfa011def621f569319&csfId=alert-banner&buildNumber=101&k=66351c0a22c6e1d67a85b355-1200px-interactive-true&h=13&b=-3
> DEV-1095: alert banner - add close button and dismissible state

- .github/workflows/tests.yaml
- package-lock.json
- package.json
- src/js/components/CookieConsentBanner/CookieConsentBanner.stories.js
- src/js/components/CookieSettingsModal/CookieSettingsModal.stories.js
- src/js/lib/analytics.js
- src/js/lib/analytics.test.js
- src/js/lib/cookies.js
- src/js/lib/cookies.test.js
- vite.config.js
I'm a little embarrassed by how little I have accomplished in the few days I've been working on this, but I'm still learning/reading about testing and there was a surprising amount of setup!
Notes:
- I'm using [vitest](https://vitest.dev/) because firebird uses vite bundling, and vitest was built to be backwards-compatible for jest. Storybook uses jest, so I'm already familiar-ish with that syntax.
- Vitest comes with some built-in testing environments for the browser: `jsdom` and `happy-dom`. I decided to use [happy-dom](https://github.com/capricorn86/happy-dom/wiki/) since it's smaller/more lightweight than jsdom, and we are already using storybook for UI tests. I only need happy-dom for browser functions (`window`, `document`, etc.)
- Using `istanbul` for coverage: `npm run coverage` …
> Cookie tests

- src/js/components/FeedbackFormBasic/FeedbackFormBasic.stories.js
- src/js/components/FeedbackFormBasic/index.svelte
- src/js/components/FeedbackFormCatalog/index.svelte
- src/js/components/FeedbackFormContent/index.svelte
- src/scss/styles.scss
This PR addresses two deque issues regarding the feedback form:
issue #71: [1727249](https://axeauditor.dequecloud.com/test-run/b2613a94-fe0b-11ee-96ce-dfcb37e53e3c/issue/6a697dd4-fe27-11ee-bc1f-9f18b5e39269?sortField=severity&sortDir=desc&page=0&issuesCount=&filter%5Bcomponent_number%5D=1&row=0) green check mark validation on form fields lacking alternate text
issue #75: [1727235](https://axeauditor.dequecloud.com/test-run/b2613a94-fe0b-11ee-96ce-dfcb37e53e3c/issue/d5e1e160-fe26-11ee-8084-d3b22a82817e?sortField=severity&sortDir=desc&page=0&issuesCount=&filter%5Bcomponent_number%5D=1&row=6) form validation error messages not being announced by screen reader
After discussion with Ange and Gayathri, we decided to remove the "valid" styles on feedback forms instead of adding text to the …
> DEV-1165: feedback form issues

- src/js/components/AdvancedSearchForm/index.svelte
- src/js/components/FeedbackFormCatalog/index.svelte
- src/js/components/FilterableSelection.svelte
- src/scss/styles.scss
Resolves some of #71 , #72 
Fixes for critical advanced search form issues:
- [1727510](https://axeauditor.dequecloud.com/test-run/b2613a94-fe0b-11ee-96ce-dfcb37e53e3c/issue/136cd630-fe3f-11ee-b5ef-37a650e942e8?sortField=ordinal&sortDir=asc&filter%5Bpage_number%5D=6&row=0) radio button does not have role and/or state 
- this was _close_ to being right, so it was an easy fix. the `id` attribute of the radio `<input>` and the `for` attribute of its corresponding `<label>` not only have to match, they must be _unique_. they matched before but were not unique, so I added an extra variable to the `id`/`for` combo and now we're good 👍 
- [1727483](https://axeauditor.dequecloud.com/test-run/b2613a94-fe0b-11ee-96ce-dfcb37e53e3c/issue/848ccb44-fe3b-11ee-8829-bbb441666957?activeTab=dt-issue&page=0&p …
> Dev 1165 advanced search form

- src/js/components/Navbar/index.svelte
Fixes #73 and [1727026](https://axeauditor.dequecloud.com/test-run/b2613a94-fe0b-11ee-96ce-dfcb37e53e3c/issue/302de104-fe0f-11ee-ac5b-ff3565d28288?sortField=severity&sortDir=desc&page=0&issuesCount=&filter%5Bcomponent_number%5D=1&row=5) _expand/collapse on search bar isn't setting aria expanded correctly_
Added `aria-expanded` attribute to the Search icon in the navbar to alert screen readers when the search bar is open or closed.
This fix is staged on dev-3 (vpn required): https://dev-3.www.hathitrust.org/
If you inspect the "search 🔍 " button in the navbar, it should now have an `aria-expanded` attribute set to `true` if the search bar is toggled to open (default on most pages). Toggle it closed, and the attribute should be set to `false`.
> DEV-1174: add aria-expanded for navbar search toggle

- src/js/components/CollectionEditModal/index.svelte
- src/js/components/CollectionsToolbar/index.svelte
Fixes issue #77 and deque issues [1728595](https://axeauditor.dequecloud.com/test-run/b2613a94-fe0b-11ee-96ce-dfcb37e53e3c/issue/894525ee-0086-11ef-a8dd-db78ee811ab9?viewMode=issues&sortField=ordinal&sortDir=asc&filter%5Bcomponent_number%5D=6&row=1), [1727518](https://axeauditor.dequecloud.com/test-run/b2613a94-fe0b-11ee-96ce-dfcb37e53e3c/issue/5ed7f8f2-fe3f-11ee-8326-b71c7e04ea6a?sortField=severity&sortDir=desc&page=0&issuesCount=&row=5&filter%5Bpage_number%5D=0), [1728277](https://axeauditor.dequecloud.com/test-run/b2613a94-fe0b-11ee-96ce-dfcb37e53e3c/issue/0a3e3cbc-005a-11ef-8764-cf40999bf5e1?viewMode=issues&sortField=ordinal&sortDir=asc&row=0&filter%5Bpage_number%5D=5)
This modal is a form, and the radio buttons under "Is this collection visible to others?" weren't accessible due to a …
> DEV-1179: small component fixes

- src/js/components/FeedbackFormBasic/index.svelte
- src/js/components/FeedbackFormCatalog/index.svelte
- src/js/components/FeedbackFormContent/index.svelte
- src/js/components/FeedbackFormModal/index.svelte
- src/js/components/Modal/index.svelte
- src/js/components/Navbar/index.svelte
The last couple fixes for the feedback form and feedback modal
All three feedback forms were missing "autocomplete" HTML attributes on name and email fields, so I added them. See `FeedbackFormBasic/index.svelte`, `FeedbackFormCatalog/index.svelte`, and `FeedbackFormContent/index.svelte`.
To test: on [dev-3](https://dev-3.www.hathitrust.org/), open the feedback form using the GET HELP dropdown in the navbar. Use dev tools to inspect the name input element and see the autocomplete attribute set to "name". The email input element has the autocomplete attribute set to "email".
When any modal is closed, in order to remain accessible, the browser/user's focus should be returned to the element that triggered the opening of the modal. In this case, the triggering element is in the navbar dropdown …
> DEV-1177: finish up feedback form fixes

- src/js/components/AdvancedSearchForm/index.svelte
- src/js/components/CookieConsentBanner/index.svelte
- src/js/components/SearchBar/index.svelte
- src/scss/apps.scss
- src/scss/styles.scss
The theme of this pull request is 🌈 colors 🎨 . The problems addressed with these color updates are contrast between the background color and color of specific text areas, form element borders, striped tables, and focus indicators throughout the website and applications. Fixes issue #78 
These fixes have been staged on dev-3:
- [website](https://dev-3.www.hathitrust.org/)
- [search results](https://dev-3.babel.hathitrust.org/cgi/ls?q1=elephant&field1=ocr&a=srchls&ft=ft&lmt=ft)
- [page turner](https://dev-3.babel.hathitrust.org/cgi/pt?id=umn.31951p00906792z&seq=3)
Deque "checkpoints" we can consider complete: 
- [Color contrast (regular text)](https://axeauditor.dequecloud.com/test-run/b2613a94-fe0b-11ee-96ce-dfcb37e53e3c/issues?sortField=ordinal&sortDir=asc&filter%5Bidentifier%5D=1.4.3.a) …
> DEV-1180: contrast colors and universal focus indicator

- src/js/components/Modal/index.svelte
- src/js/components/Navbar/index.svelte
Re: @mwarin's suggestion in PR #88 
> 1: As a user relying on keyboard/screen-reader, I think it would be neat if the form modal would close on ESC, rather than having to tab back to the beginning of the form to close it. This might be accessibility-heresy, so take that as the personal preference it is.
I did some testing and found an additional bug: my original fix returned the focus to the GET HELP link when you use the CLOSE button on the modal, but the `ESC` key returned the focus back to the body element. 
This event listener (with a few `.focus()` methods thrown in for fallback/good measure) picks up on `ESC` keys and invokes the `hide()` function (which sets the focus back to GET HELP).
This closes issue #89.
**To test:** head over to [dev-3](https://dev-3.www.hathitrust.org/) and …
> issue #89: add event listener for escape key

- src/js/components/Navbar/index.svelte
- src/scss/styles.scss
The navbar logo had a visible focus indicator in the apps but not on the website. The element received focus without issue, but there was no visible focus indicator. I changed the display to `block` instead of `inline` and that fixed the issue.
I missed that we use the "active" class on some buttons (the ones that came up during testing are in page turner, but they may be elsewhere, too!). "active" buttons had their own focus styles from bootstrap, so I overrode those.
The animations that are triggered on focus are not consistent and are a little distracting. I set `transition: unset` in all of our focus state styles to remove animations on focus.
- Hop on your VPN and head over to https://dev-3.www.hathitrust.org/. Tab through to the navbar logo and see the blue focus indicator. 
- Pick …
> #92: focus indicator bug fixes

- src/js/components/CollectionsToolbar/index.svelte
- src/scss/apps.scss
- src/scss/styles.scss
This is only an issue for elements with a `bg-secondary` or `bg-dark` utility class. Our focus blue doesn't have enough contrast against the dark gray or black, so Gayathri and I decided to flip the blue and white of the universal focus style, but only for these components.
Previous:
With this update:
Black toolbar element in page turner:
With this fix:
And removes this bootstrap bleed through focus style with an orange outline (all form elements, not just dropdown/selects):
Updated:
@giramesh, does this look good to you on dev-3?
> fix form field focus styles

- src/js/components/AdvancedSearchForm/index.svelte
- src/js/components/CookieConsentBanner/index.svelte
This issue occurred in Advanced Search. Turns out there were _multiple_ reflow issues. The issue flagged by deque is only that the placeholder text in the search input field was cut off when zoomed in. It needs to be fully visible.
Issue:
What we learned as I starting debugging this is that the input fields should've started wrapping but they couldn't because a single element later in the page was set to `nowrap` which caused other elements to not collapse when they should've. [Video link for posterity.](https://hathitrust.slack.com/files/U044M495QEN/F07G7QRRHAQ/screenshare_-_2024-08-08_2_52_07_pm.webm)
@giramesh designed a mobile view for the main search fields and flexbox made it easy to change those without rearranging the markup.
On dev-3 at 400%:
**To test:** Go to [dev-3 advanced …
> DEV-1175/#91: Reflow issues

- src/scss/styles.scss
For the TIFF restrictions note in [babel PR 46](https://github.com/hathitrust/babel/pull/46), we need to add the bootstrap `cyan-700` shade to our utility class list of text colors.
> add cyan to utility classes

- src/js/components/CookieSettingsModal/index.svelte
Like it says on the tin, I removed "YouTube" from the content of the cookie modal.
Staged on dev-3 if you want to take a look: [dev-3.www.hathitrust.org](https://dev-3.www.hathitrust.org/)
If you get the cookie banner, you can click on "Customize cookies >" to get the modal, but if you've accepted cookies on dev-3 recently, you can scroll down to the footer and select "Cookie Settings". Then open the "Marketing" accordion to see that the content has been updated.
> DEV-1292: remove youtube language from cookie settings modal

- src/js/components/FeedbackFormModal/FeedbackFormModal.stories.js
- src/js/components/FeedbackFormModal/index.svelte
See [TTO-282](https://hathitrust.atlassian.net/browse/TTO-282) for context.
I updated the dates in the feedback form modal to correspond with this year's dates. The _days_ of the message are the same as last year's (22nd-2nd), so that didn't change. 
I also added a mobile version of the story for this message to double check the mobile styles are correct this time around. You can see the new story here: https://656a2bfa011def621f569319-dldpyevyjc.chromatic.com/?path=/story/feedback-form-modal--winter-break-mobile
Val already gave her approval for the message, so we're good to go! 
[TTO-282]: https://hathitrust.atlassian.net/browse/TTO-282?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> TTO-282: update winter break date range

- src/js/components/AdvancedSearchForm/index.svelte
- src/js/components/FilterableSelection.svelte
related to hathitrust/babel#70 and hathitrust/catalog#65 
This adds an "Original Location" filter option to the advanced search component. 
See this in action on dev-3 [catalog](https://dev-3.catalog.hathitrust.org/Search/Advanced) and [ls](https://dev-3.babel.hathitrust.org/cgi/ls?a=page&page=advanced) (vpn required).
I added another `FilterableSelection` component to match the 'Language' and 'Format' selection options. This version, however, sets the 'multiple' prop to `false` because selecting two locations did not work in either `catalog` or `ls`.
I updated the functions for `catalog` and `ls` search URLs. The form itself is identical, but the URLs for searching in `catalog` and `ls` have slight differences. I added functions for appending an `htsource` facet/filter to the search …
> DEV-900: add 'original location' filter to advanced search

- src/js/lib/staging.js
This handy/wild staging utility rewrites links on dev servers to match the subdomain/protocol of the server. When I was removing the cookie banner from pt embeds (DEV-1116), something weird was happening with rewriting the handle URLs for the iframe. Aaron helped me track down this function, and I refactored to make it a bit more robust.
I kept the original if statement but nested it inside another if statement (🫠) just in case it's necessary for something that I am unaware of.
This might not be the best code in the world, but it doesn't affect prod and I needed to add this to stage the work for hathitrust/babel#73
To test: The pt embed iframes are now loading correctly with the minimal UI look. This code isn't staged on the test server yet, so the old function is still causing the …
> DEV-1116: update staging links utility

- README.md
- src/js/components/AlertBanner/AlertBanner.stories.js
- src/js/components/AlertBanner/BannerMessage.svelte
- src/js/components/AlertBanner/index.svelte
- src/scss/apps.scss
Finishing up DEV-1095 with a few additions to the original outage notifications:
- add [message-only variant](https://656a2bfa011def621f569319-zhhaerpzjb.chromatic.com/iframe.html?args=&globals=viewport:bsLg&id=alert-banner--message-only)
- add ["brand" style variant](https://656a2bfa011def621f569319-zhhaerpzjb.chromatic.com/iframe.html?args=&globals=viewport:bsLg&id=alert-banner--brand)
- hook the alerts up to external json data
- fix accessibility issues
- add stories to [storybook](https://656a2bfa011def621f569319-zhhaerpzjb.chromatic.com/)
- update README with instructions for alert json data
The biggest hurdle for this update was the external json data. A challenge I ran into was making sure this component could reach the data, whether the component is at www, catalog, or babel. …
> DEV-1095: Outage notifications

- src/js/components/CollectionEditModal/index.svelte
- src/js/components/CollectionsToolbar/index.svelte
From `mb` [landing page](https://babel.hathitrust.org/cgi/mb?colltype=featured), when a user clicks "New Collection" (from the collection toolbar under "Featured collections" and above the listing of collections), the New Collection (also sometimes says Edit Collection, depending on the situation) modal appears. Regardless of login status, this modal tells the user their new collection will be temporary unless they log in (even if the user is already logged in).
The modal already had a `userIsAnonymous` variable but it wasn't getting set in this context (via the _results_ toolbar in `mb`) so the change in UI never happened. (To be fair, this variable  _is_ getting set when you create a collection via `ls` _collection_ toolbar). Instead of relying on passing down the variable from the `ls` …
> DEV-1587: fix collection edit modal bugs

- src/js/lib/utils.js
This is a fix for playwright testing and only affects development environments, and specifically development environments with a hostname of `apache-host` (which should only be playwright tests).
> add 'apahce-test' as localhost prefix for domains

- src/cloudflare.html
- src/cloudflare/index.html
- vite.config.js
There are two changes here:
1. the HTML page for cloudflare errors
2. updates to the vite config for building the cloudflare page for production
I will squash commits before merging this one!
> DEV-1645: cloudflare error page

- src/js/components/AcceptableUseBanner/index.svelte
- src/js/components/AlertBanner/BannerMessage.svelte
- src/js/components/Navbar/index.svelte
- src/js/lib/cookies.js
- src/js/lib/cookies.test.js
- src/js/lib/utils.js
See comments on individual PRs. For testing with https://github.com/hathitrust/babel/pull/113
> ETT-310, ETT-309: Role switcher for resource sharing; fixes for cookie handling

- src/js/components/Modal/index.svelte
- src/js/components/Navbar/Navbar.stories.js
- src/js/components/Navbar/index.svelte
- src/js/components/RoleSwitchModal/index.svelte
The changes here are a11y fixes that @giramesh identified during testing of ETT-324 and ETT-347:
- fix the label for the notifications button 
- fix the modal "cancel" button style conflict in wordpress
- associate the “current role” elements with the “my account” button via aria-labelledby; remove the "current role" label from the "switch role" button
- add state change language to submit button icon label
- on modal close (either X button or Cancel button) via keyboard, return focus to navbar/My Account button
These fixes are so small, I'm not sure there's much to review. This is staged on dev-3 if you want to run through the log in and switch role process with your keyboard/screen reader, you could double check that the announcements make sense.
These fixes changed the markup in the …
> ETT-429: a11y fixes for resource sharing UI

- src/js/components/RoleSwitchModal/index.svelte
I added copy to the role switch modal for RS, fixed link color to meet contrast ratio standards, and updated the list item styles to closer match the design.
Edit to add: @giramesh caught that an email address in the CAA copy was not actually a hyperlink, so I fixed that, too.
Storybook: https://656a2bfa011def621f569319-jdbravqpxv.chromatic.com/?path=/story/role-switch-modal--desktop-switchable-role-not-activated&globals=viewport:bsLg
Also staged on dev-3.
> ETT-313: RS Terms of Service copy
